# Generated by Django 6.0.2 on 2026-02-27 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('sorted_weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sorted_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrewTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='profiles.crew')),
            ],
            options={
                'ordering': ['crew', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wannabe_id', models.CharField(blank=True, max_length=200)),
                ('planned_meetup', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chief', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='profiles.crew')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='profiles.crewteam')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_memberships', to='profiles.profile')),
            ],
            options={
                'ordering': ['crew', 'team', 'is_chief', 'profile__user__first_name', 'profile__user__last_name'],
            },
        ),
    ]
