# Generated by Django 6.0.2 on 2026-03-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='planned_meetup',
        ),
    ]
