# Generated by Django 4.1.7 on 2023-03-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctm', '0005_remove_task_min_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timeslot',
        ),
        migrations.DeleteModel(
            name='TaskTimeSlotCrew',
        ),
    ]
