version: '3.8'

services:
  app:
    build: .
    command: gunicorn tgctm.wsgi --bind 0.0.0.0:8020 --workers 3
    restart: unless-stopped
    ports: 
      - "8020"
    env_file:
      - ./.env
    depends_on:
      - db
  
  nginx:
    # image: nginx:alpine
    restart: unless-stopped
    build:
      context: .
      dockerfile: _config/nginx/Dockerfile
    ports: 
      - "8124:80"
    volumes:
      - ./_config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./.env

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./.env

volumes:
  mariadb_data: