# Generated by Django 6.0.2 on 2026-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_info',
            field=models.TextField(blank=True),
        ),
    ]
