load_module modules/ngx_http_brotli_static_module.so;

worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  server {
    listen 80 default_server;
    server_name _;

    root /var/www/html/;
    index index.html;

    location ~ ^/(static|assets)/ {
      brotli_static on;
      gzip_static on;

      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable" always;

      try_files $uri =404;
    }

    location / {
      proxy_http_version 1.1;
      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://app/;
    }
  }
}
