"""
Django settings for ctm project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


APP_NAME = "CTM"
APP_DESCRIPTION = "Oppgavehåndtering og loggføring for The Gathering"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "development")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true") == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://127.0.0.1,http://localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ctm
    "apps.profiles",
    # todo: "apps.kitchen",
    "apps.tasks",
    # design
    "tailwind", "theme",
    "crispy_forms", "crispy_tailwind",
    "fontawesomefree",
    "django_google_fonts",
    "chartjs",
    # authentication
    "social_django",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = (
    "social_core.backends.keycloak.KeycloakOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.constants",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends." + os.environ.get("DB_ENGINE", "sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DB_USER", "user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "password"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  { "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator" },
  { "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator" },
  { "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator" },
  { "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator" },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "nb"
USE_I18N = True
TIME_ZONE = "Europe/Oslo"
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.environ.get("STATIC_ROOT", "./static_built")

STATICFILES_DIRS = [
  BASE_DIR / "static",
]

STORAGES = {
  "default": { "BACKEND": "django.core.files.storage.FileSystemStorage" },
  "staticfiles": { "BACKEND": "compress_staticfiles.storage.CompressStaticFilesStorage" },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Tailwind

TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = [ "127.0.0.1" ]
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Google fonts

GOOGLE_FONTS = [
  "Noto Color Emoji:wght@400",
]

# Progressive Web App
PWA_APP_NAME = APP_NAME
PWA_APP_DESCRIPTION = APP_DESCRIPTION
PWA_APP_THEME_COLOR = "#0C7779"
PWA_APP_BACKGROUND_COLOR = "#005461"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_ORIENTATION = "any"
PWA_APP_START_URL = "/"
PWA_APP_STATUS_BAR_COLOR = "default"
PWA_APP_ICONS = [
  { "src": "/static/icon/ctm-32px.png", "sizes": "32x32" },
  { "src": "/static/icon/ctm-72px.png", "sizes": "72x72" },
  { "src": "/static/icon/ctm-128px.png", "sizes": "128x128" },
  { "src": "/static/icon/ctm-512px.png", "sizes": "512x512" },
]
PWA_APP_ICONS_APPLE = [
  { "src": "/static/icon/ctm-32px.png", "sizes": "32x32" },
  { "src": "/static/icon/ctm-72px.png", "sizes": "72x72" },
  { "src": "/static/icon/ctm-128px.png", "sizes": "128x128" },
  { "src": "/static/icon/ctm-512px.png", "sizes": "512x512" },
]
PWA_APP_SPLASH_SCREEN = []
#  {
#    "src": "/static/images/icons/splash-640x1136.png",
#    "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
#  }
#]
PWA_APP_DIR = "ltr"
PWA_APP_LANG = LANGUAGE_CODE
PWA_APP_SHORTCUTS = []
#  {
#    "name": "Shortcut",
#    "url": "/target",
#    "description": "Shortcut to a page in my application"
#  }
#]
PWA_APP_SCREENSHOTS = []
#    {
#      "src": "/static/images/icons/splash-750x1334.png",
#      "sizes": "750x1334",
#      "type": "image/png"
#    }
#]

# TGBT IDAM Settings

IDAM_API_URL=os.environ.get("TGBT_IDAM_API_URL", "https://tgbt-idam.gathering.org/")
IDAM_API_KEY=os.environ.get("TGBT_IDAM_API_KEY")

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)

# Add you connection settings here
SOCIAL_AUTH_KEYCLOAK_KEY = os.environ.get("SOCIAL_AUTH_KEYCLOAK_KEY")
SOCIAL_AUTH_KEYCLOAK_SECRET = os.environ.get("SOCIAL_AUTH_KEYCLOAK_SECRET")
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = os.environ.get("SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY")
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = os.environ.get("SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL")
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = os.environ.get("SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL")
SOCIAL_AUTH_KEYCLOAK_ID_KEY = os.environ.get("SOCIAL_AUTH_KEYCLOAK_ID_KEY")
SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL = os.environ.get("SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL")
SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA=[("refresh_token","refresh_token")]

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

LOGIN_REDIRECT_URL = "/"

# DateTime settings
DATETIME_FORMAT = "Y-m-d H:M:S"
TIME_FORMAT = "H:M:S"
SHORT_DATETIME_FORMAT = "m/d/Y H:M:S"

# Slack
SLACK_CLIENT_TOKEN = os.environ.get("SLACK_CLIENT_TOKEN")
